Repository ToyVallet/swifty-fe, pull requests merged in 2024-05, with the labels that each got.

#2 feat: footer
  app/[locale]/layout.tsx
  app/components/common/footer.tsx
  tailwind.config.ts
Labels: 💬 리뷰 요청

#13 Main page 작업
  .storybook/main.ts
  .storybook/preview.tsx
  app/[locale]/(back-nav)/lineup/page.tsx
  app/[locale]/(root-nav)/festivals/page.tsx
  app/[locale]/(root-nav)/layout.tsx
  app/[locale]/(root-nav)/page.tsx
  app/[locale]/layout.tsx
  app/components/common/ad-banner.tsx
  app/components/common/carousel/index.tsx
  app/components/common/carousel/tile.tsx
  app/components/common/hero/hero-tile.tsx
  app/components/common/link.tsx
  app/components/common/navigation/index.tsx
  app/components/home/festival-tile.tsx
  app/components/home/index.ts
  app/components/home/lineup-tile.tsx
  app/components/home/tile-header.tsx
  app/lib/mock/data.ts
  app/lib/types/festival.ts
  app/lib/types/index.ts
  app/lib/types/types.ts
  messages/en.json
  messages/ko.json
  public/images/banner.png
  stories/common/Carousel.stories.tsx
  stories/components/home/festival-tile.stories.tsx
  stories/page/fastivals.stories.tsx
  stories/page/main.stories.tsx
  yarn.lock
Labels: 💬 리뷰 요청

#14 date selector 및 라인업 페이지
  app/[locale]/(back-nav)/lineup/page.tsx
  app/[locale]/(back-with-logo)/festival/[id]/action.ts
  app/[locale]/(back-with-logo)/festival/[id]/page.tsx
  app/[locale]/(back-with-logo)/layout.tsx
  app/[locale]/(root-nav)/action.ts
  app/[locale]/(root-nav)/page.tsx
  app/components/common/carousel/fade-overlay.tsx
  app/components/common/carousel/tile.tsx
  app/components/common/hero/hero-tile.tsx
  app/components/common/hero/index.tsx
  app/components/common/index.ts
  app/components/common/link.tsx
  app/components/common/menu-tiles/index.tsx
  app/components/common/menu-tiles/tile.tsx
  app/components/common/navigation/index.tsx
  app/components/festival/index.ts
  app/components/festival/line-up-section/date-selector/date-block.tsx
  app/components/festival/line-up-section/date-selector/index.tsx
  app/components/festival/line-up-section/index.tsx
  app/components/festival/line-up-section/line-up-card.tsx
  app/components/festival/top-card.tsx
  app/components/home/index.ts
  app/components/home/menu-tiles/index.tsx
  app/globals.css
  app/layout.tsx
  app/lib/mock/data.ts
  app/lib/types/festival.ts
  app/lib/types/index.ts
  app/lib/types/line-up.ts
  app/lib/types/locale.ts
  app/lib/utils/parser/format-date.ts
  app/lib/utils/parser/parse-festival-date.ts
  next.config.mjs
  package.json
  stories/common/Carousel.stories.tsx
  stories/components/home/lineup-tiles.stories.tsx
  yarn.lock
Labels: 💬 리뷰 요청, 🔨 기능

#16 Build 작업
  app/[locale]/(back-nav)/(padded)/events/page.tsx
  app/[locale]/(back-nav)/(padded)/find-my/id/complete/page.tsx
  app/[locale]/(back-nav)/(padded)/find-my/page.tsx
  app/[locale]/(back-nav)/(padded)/find-my/password/complete/page.tsx
  app/[locale]/(back-nav)/(padded)/jeomshim/page.tsx
  app/[locale]/(back-nav)/(padded)/layout.tsx
  app/[locale]/(back-nav)/(padded)/my-tickets/action.ts
  app/[locale]/(back-nav)/(padded)/my-tickets/page.tsx
  app/[locale]/(back-nav)/(padded)/mypage/page.tsx
  app/[locale]/(back-nav)/(padded)/need-reverification/page.tsx
  app/[locale]/(back-nav)/(padded)/notice/page.tsx
  app/[locale]/(back-nav)/(padded)/password/page.tsx
  app/[locale]/(back-nav)/(padded)/password/schema.ts
  app/[locale]/(back-nav)/(padded)/signup/complete/page.tsx
  app/[locale]/(back-nav)/(padded)/signup/page.tsx
  app/[locale]/(back-nav)/(padded)/sms/page.tsx
  app/[locale]/(back-nav)/(padded)/stamp/[missionId]/page.tsx
  app/[locale]/(back-nav)/(padded)/ticketing/[eventId]/action.ts
  app/[locale]/(back-nav)/(padded)/ticketing/[eventId]/page.tsx
  app/[locale]/(back-nav)/(padded)/ticketing/[eventId]/result/page.tsx
  app/[locale]/(back-nav)/(padded)/ticketing/action.ts
  app/[locale]/(back-nav)/(padded)/ticketing/page.tsx
  app/[locale]/(back-nav)/(padded)/verify/action.ts
  app/[locale]/(back-nav)/(padded)/verify/page.tsx
  app/[locale]/(back-nav)/(padded)/verify/schema.ts
  app/[locale]/(back-nav)/(padded)/verify/terms.tsx
  app/[locale]/(back-nav)/admin/action.ts
  app/[locale]/(back-nav)/admin/layout.tsx
  app/[locale]/(back-nav)/admin/page.tsx
  app/[locale]/(back-nav)/layout.tsx
  app/[locale]/(back-nav)/lineup/actions.ts
  app/[locale]/(back-nav)/lineup/page.tsx
  app/[locale]/(back-nav)/login/layout.tsx
  app/[locale]/(back-nav)/login/page.tsx
  app/[locale]/(dark-scheme)/layout.tsx
  app/[locale]/(dark-scheme)/stamp/action.ts
  app/[locale]/(dark-scheme)/stamp/layout.tsx
  app/[locale]/(dark-scheme)/stamp/mission-info.ts
  app/[locale]/(dark-scheme)/stamp/page.tsx
  app/[locale]/(root-nav)/action.ts
  app/[locale]/(root-nav)/layout.tsx
  app/[locale]/(root-nav)/page.tsx
  app/components/admin/keypad/index.tsx
  app/components/admin/result-tile/student-info.tsx
  app/components/common/carousel/tile.tsx
  app/components/common/hero/hero-tile.tsx
  app/components/my-tickets/ticket.tsx
  app/components/ticketing/card.tsx
  app/hooks/use-auth.ts
  app/lib/constants.ts
  app/lib/mock/type.ts
  app/lib/schema/schema.ts
  app/lib/utils/parser/parse-festival-date.ts
  stories/components/admin/result-tile.stories.tsx
  stories/page/fastivals.stories.tsx
  stories/page/main.stories.tsx
Labels: 💬 리뷰 요청, 🥳 배포

#21 chore: 푸터에서 통신판매업 신고번호 제거
  app/components/common/footer.tsx
Labels: 🎸 기타, 💬 리뷰 요청

#24 19 축제리스트 수정
  app/[locale]/(root-nav)/festivals/page.tsx
  app/components/common/ad-banner.tsx
  app/components/common/carousel/tile.tsx
Labels: ✨ 개선점, 🐞 버그

#25 v0.1.0
  app/[locale]/(root-nav)/festivals/page.tsx
  app/components/common/ad-banner.tsx
  app/components/common/carousel/tile.tsx
  app/components/common/footer.tsx
Labels: 🥳 배포

#29 로고 이미지 alpha 버전으로 교체
  public/icons/logo.svg
Labels: 💬 리뷰 요청, 💅 스타일

#31 fix: backgroundColor 수정
  app/globals.css
Labels: 💬 리뷰 요청, 💅 스타일

#32 chore: 이미지 전부 교체
  app/favicon.ico
  app/opengraph-image.png
  app/twitter-image.png
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/android-icon-144x144.png
  public/android-icon-192x192.png
  public/android-icon-36x36.png
  public/android-icon-48x48.png
  public/android-icon-72x72.png
  public/android-icon-96x96.png
  public/apple-icon-114x114.png
  public/apple-icon-120x120.png
  public/apple-icon-144x144.png
  public/apple-icon-152x152.png
  public/apple-icon-180x180.png
  public/apple-icon-57x57.png
  public/apple-icon-60x60.png
  public/apple-icon-72x72.png
  public/apple-icon-76x76.png
  public/apple-icon-precomposed.png
  public/apple-icon.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon-96x96.png
  public/favicon.ico
  public/icons/feasta-logo.png
  public/icons/orbit_logo.png
  public/icons/shield.png
  public/icons/ticket.svg
  public/icons/u-mate-logo.webp
  public/images/danfesta-bg-1.png
  public/images/perspaleta2_0020.png
  public/images/stamp/universe_bg.jpeg
  public/images/stamp/스탬프판_문체-02.webp
  public/images/stamp/스탬프판_문체-03.webp
  public/images/stamp/스탬프판_문체-04.webp
  public/images/stamp/스탬프판_문체-05.webp
  public/images/stamp/스탬프판_문체-06.webp
  public/images/stamp/스탬프판_문체-07.webp
  public/images/stamp/스탬프판_문체-08.webp
  public/images/stamp/스탬프판_문체.png
  public/images/stamp/스탬프판_문체_배경.webp
  public/ms-icon-144x144.png
  public/ms-icon-150x150.png
  public/ms-icon-310x310.png
  public/ms-icon-70x70.png
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
  public/site.webmanifest
  public/thumbnail.webp
  public/vercel.svg
Labels: 🎸 기타, 💬 리뷰 요청

#34 fix: 캐러셀 내부 텍스트 콘텐츠 디자인 일치화
  app/components/common/carousel/tile.tsx
  app/components/common/hero/hero-tile.tsx
  app/components/common/navigation/index.tsx
Labels: 💬 리뷰 요청, 💅 스타일

#35 축제 리스트 캐러셀 모션 관련 option 추가
  app/components/common/carousel/index.tsx
Labels: 💬 리뷰 요청, 💅 스타일

#38 feat: 캐러셀 루프, auto play 추가
  app/[locale]/(root-nav)/layout.tsx
  app/components/common/carousel/index.tsx
  package.json
  yarn.lock
Labels: 💬 리뷰 요청, 🔨 기능

#39 add button hover
  app/[locale]/(root-nav)/page.tsx
  app/components/admin/qr-reader.tsx
  app/components/common/button/index.tsx
  app/components/common/button/motion.ts
  app/components/common/form/phone/index.tsx
  app/components/common/form/terms.tsx
  app/components/common/link.tsx
  app/components/common/side-nav/index.tsx
  app/components/my-tickets/qr-code.tsx
  app/components/ticketing/form.tsx
  app/components/ticketing/refetch-button.tsx
  stories/common/Button.stories.tsx
Labels: 💬 리뷰 요청

#40 이미지 표시되지않음 처리
  app/[locale]/(back-with-logo)/festival/[id]/page.tsx
  app/components/common/carousel/tile.tsx
  app/components/common/hero/hero-tile.tsx
  app/components/common/image-with-fallback.tsx
  app/components/common/index.ts
  public/images/fallback-festival.png
  public/images/fallback-hero.png
  stories/common/image-with-fallback.stories.tsx
Labels: 💬 리뷰 요청, 🔨 기능
